# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: swordsman
dist: dist/production
before:
  hooks:
    - go mod tidy
builds:
  - main: ./game/
    id: "game"
    binary: swordsman_game
    # no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
  - main: ./account/
    id: "account"
    binary: swordsman_account
    # no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: x86
      amd64: x64
    files:
      - config.json
      - public
    format: zip
# checksum:
#   name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
